import React, { useState, useEffect } from 'react';
import { Sparkles, Check, Compass, Car, Zap, Utensils, ShoppingBag, Loader, AlertTriangle, ShieldCheck } from 'lucide-react';

export default function AIAdvisor({ user, logs, simulation, API_BASE, onAdopt }) {
  const [recommendations, setRecommendations] = useState([]);
  const [loading, setLoading] = useState(false);
  const [adoptingId, setAdoptingId] = useState(null);
  const [error, setError] = useState('');
  const [feedbackMsg, setFeedbackMsg] = useState('');

  const fetchRecommendations = async () => {
    setLoading(true);
    setError('');
    setFeedbackMsg('');
    try {
      // POST current local client state to backend AI Engine
      const res = await fetch(`${API_BASE}/recommendations`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ user, logs, simulation })
      });
      if (!res.ok) throw new Error('Failed to retrieve personalized recommendations.');
      const data = await res.json();
      setRecommendations(data);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchRecommendations();
  }, [logs.length]); // Refresh recommendations if number of logs change

  const handleAdoptRecommendation = (rec) => {
    setAdoptingId(rec.id);
    setError('');
    setFeedbackMsg('');

    // Check if duplicate
    if (simulation.plannedActions.includes(rec.title)) {
      setFeedbackMsg(`"${rec.title}" is already in your Simulator action plan!`);
      setAdoptingId(null);
      return;
    }

    const updatedActions = [...simulation.plannedActions, rec.title];
    const updatedSavings = parseFloat(((simulation.estimatedSavings || 0) + rec.estimatedSavings).toFixed(1));
    const targetPercent = Math.min(Math.round(simulation.targetReductionPercentage + 5), 50);

    // Call local save handler
    onAdopt({
      targetReductionPercentage: targetPercent,
      plannedActions: updatedActions,
      estimatedSavings: updatedSavings
    });

    setFeedbackMsg(`"${rec.title}" adopted! Added to your Reduction Simulator plan.`);
    setAdoptingId(null);
  };

  const getCategoryIcon = (category) => {
    switch (category) {
      case 'transport': return <Car size={16} />;
      case 'electricity': return <Zap size={16} />;
      case 'food': return <Utensils size={16} />;
      case 'purchase': return <ShoppingBag size={16} />;
      default: return <Compass size={16} />;
    }
  };

  const getDifficultyColor = (diff) => {
    switch (diff?.toLowerCase()) {
      case 'easy': return { bg: 'hsla(var(--accent-emerald), 0.15)', color: 'hsl(var(--accent-emerald))' };
      case 'medium': return { bg: 'hsla(var(--accent-gold), 0.15)', color: 'hsl(var(--accent-gold))' };
      case 'hard': return { bg: 'hsla(var(--accent-coral), 0.15)', color: 'hsl(var(--accent-coral))' };
      default: return { bg: 'hsla(var(--text-secondary), 0.15)', color: 'hsl(var(--text-secondary))' };
    }
  };

  return (
    <div className="animate-fade-in" style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
      
      {/* Advisor Header */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '16px' }}>
        <div>
          <h1 style={{ fontSize: '2rem', fontWeight: '800', letterSpacing: '-0.5px', display: 'flex', alignItems: 'center', gap: '12px' }}>
            <Sparkles size={28} style={{ color: 'hsl(var(--accent-cyan))' }} />
            AI Advisor
          </h1>
          <p style={{ color: 'hsl(var(--text-secondary))' }}>
            Personalized, carbon-reducing recommendations generated by Google Gemini.
          </p>
        </div>
        <button 
          className="btn btn-secondary" 
          onClick={fetchRecommendations} 
          disabled={loading}
          style={{ gap: '8px' }}
        >
          {loading ? 'Analyzing...' : 'Refresh Advice'}
        </button>
      </div>

      {feedbackMsg && (
        <div style={{ display: 'flex', alignItems: 'center', gap: '8px', color: 'hsl(var(--accent-emerald))', background: 'hsla(var(--accent-emerald), 0.1)', padding: '12px', borderRadius: 'var(--border-radius-sm)', fontSize: '0.9rem', border: '1px solid hsla(var(--accent-emerald), 0.2)' }}>
          <ShieldCheck size={18} />
          {feedbackMsg}
        </div>
      )}

      {error && (
        <div style={{ display: 'flex', alignItems: 'center', gap: '8px', color: 'hsl(var(--accent-coral))', background: 'hsla(var(--accent-coral), 0.1)', padding: '12px', borderRadius: 'var(--border-radius-sm)', fontSize: '0.9rem', border: '1px solid hsla(var(--accent-coral), 0.2)' }}>
          <AlertTriangle size={18} />
          {error}
        </div>
      )}

      {/* Recommendations Cards Grid */}
      {loading ? (
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))', gap: '20px' }}>
          {[1, 2, 3, 4].map(n => (
            <div key={n} className="glass-card" style={{ height: '220px', display: 'flex', flexDirection: 'column', gap: '16px', justifyContent: 'space-between' }}>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
                <div style={{ width: '50%', height: '20px', background: 'hsla(var(--text-primary), 0.05)', borderRadius: '4px' }}></div>
                <div style={{ width: '80%', height: '14px', background: 'hsla(var(--text-primary), 0.03)', borderRadius: '4px' }}></div>
                <div style={{ width: '90%', height: '14px', background: 'hsla(var(--text-primary), 0.03)', borderRadius: '4px' }}></div>
              </div>
              <div style={{ width: '30%', height: '32px', background: 'hsla(var(--text-primary), 0.05)', borderRadius: '4px' }}></div>
            </div>
          ))}
        </div>
      ) : recommendations.length === 0 ? (
        <div className="glass-card" style={{ textAlign: 'center', padding: '60px 20px', color: 'hsl(var(--text-muted))' }}>
          <Compass size={48} style={{ marginBottom: '16px' }} />
          <h3>No recommendations yet</h3>
          <p style={{ margin: '8px 0 20px 0' }}>Log some activities in transport, electricity, or food to get tailored advisor tips!</p>
          <button className="btn btn-primary" onClick={fetchRecommendations}>Load Engine</button>
        </div>
      ) : (
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))', gap: '20px' }}>
          {recommendations.map(rec => {
            const diffStyle = getDifficultyColor(rec.difficulty);
            return (
              <div key={rec.id} className="glass-card glass-card-ai animate-fade-in" style={{ display: 'flex', flexDirection: 'column', justifyContent: 'space-between', gap: '16px' }}>
                <div>
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '12px' }}>
                    <span style={{ 
                      display: 'inline-flex', 
                      alignItems: 'center', 
                      gap: '6px', 
                      fontSize: '0.75rem', 
                      fontWeight: '700', 
                      textTransform: 'uppercase', 
                      letterSpacing: '0.5px',
                      color: 'hsl(var(--accent-cyan))'
                    }}>
                      {getCategoryIcon(rec.category)}
                      {rec.category}
                    </span>
                    
                    <span style={{ 
                      fontSize: '0.7rem', 
                      fontWeight: '700', 
                      padding: '3px 8px', 
                      borderRadius: '12px',
                      textTransform: 'uppercase',
                      background: diffStyle.bg,
                      color: diffStyle.color
                    }}>
                      {rec.difficulty}
                    </span>
                  </div>

                  <h3 style={{ fontSize: '1.25rem', fontWeight: '800', marginBottom: '8px' }}>{rec.title}</h3>
                  <p style={{ fontSize: '0.88rem', color: 'hsl(var(--text-secondary))', lineHeight: '1.45' }}>{rec.description}</p>
                </div>

                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderTop: '1px solid hsl(var(--border-color))', paddingTop: '14px', marginTop: '4px' }}>
                  <div>
                    <span style={{ fontSize: '1.1rem', fontWeight: '800', color: 'hsl(var(--accent-emerald))' }}>
                      -{rec.estimatedSavings}
                    </span>
                    <span style={{ fontSize: '0.75rem', color: 'hsl(var(--text-muted))', marginLeft: '4px', fontWeight: '600' }}>kg CO₂e /mo</span>
                  </div>

                  <button 
                    className="btn btn-secondary" 
                    style={{ padding: '8px 16px', fontSize: '0.85rem' }} 
                    onClick={() => handleAdoptRecommendation(rec)}
                    disabled={adoptingId !== null}
                  >
                    {adoptingId === rec.id ? (
                      <Loader size={14} className="animate-spin" style={{ animation: 'spin 1s linear infinite' }} />
                    ) : (
                      <>
                        <Check size={14} />
                        Adopt Tip
                      </>
                    )}
                  </button>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
